// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"encoding/binary"
	"github.com/go-faster/errors"
)

// ClickHouse uses LittleEndian.
var _ = binary.LittleEndian

// ColUInt64 represents UInt64 column.
type ColUInt64 []uint64

// Compile-time assertions for ColUInt64.
var (
	_ ColInput  = ColUInt64{}
	_ ColResult = (*ColUInt64)(nil)
	_ Column    = (*ColUInt64)(nil)
)

// Type returns ColumnType of UInt64.
func (ColUInt64) Type() ColumnType {
	return ColumnTypeUInt64
}

// Rows returns count of rows in column.
func (c ColUInt64) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColUInt64) Reset() {
	*c = (*c)[:0]
}

// NewArrUInt64 returns new Array(UInt64).
func NewArrUInt64() *ColArr {
	return &ColArr{
		Data: new(ColUInt64),
	}
}

// AppendUInt64 appends slice of uint64 to Array(UInt64).
func (c *ColArr) AppendUInt64(data []uint64) {
	d := c.Data.(*ColUInt64)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}

// EncodeColumn encodes UInt64 rows to *Buffer.
func (c ColUInt64) EncodeColumn(b *Buffer) {
	const size = 64 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c))...)
	for _, v := range c {
		binary.LittleEndian.PutUint64(
			b.Buf[offset:offset+size],
			v,
		)
		offset += size
	}
}

// DecodeColumn decodes UInt64 rows from *Reader.
func (c *ColUInt64) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 64 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := append(*c, make([]uint64, rows)...)

	var (
		n = 0
		i = 0
	)
	const (
		unroll         = 4
		unrollByteSize = size * unroll
	)
	if len(data) > unrollByteSize {
		_ = data[:len(data)-unrollByteSize]
		for i = 0; i <= len(data)-unrollByteSize; i += unrollByteSize {
			src := [unroll]uint64{}
			const offset0 = 0 + size + size + size
			src[3] =
				binary.LittleEndian.Uint64(data[i+offset0 : i+offset0+size : i+offset0+size])
			const offset1 = 0 + size + size
			src[2] =
				binary.LittleEndian.Uint64(data[i+offset1 : i+offset1+size : i+offset1+size])
			const offset2 = 0 + size
			src[1] =
				binary.LittleEndian.Uint64(data[i+offset2 : i+offset2+size : i+offset2+size])
			const offset3 = 0
			src[0] =
				binary.LittleEndian.Uint64(data[i+offset3 : i+offset3+size : i+offset3+size])
			copy(v[n:n+unroll:n+unroll], src[:])
			n += unroll
		}
	}
	for _ = i; i < len(data); i += size {
		v[n] =
			binary.LittleEndian.Uint64(data[i:])
		n++
	}
	*c = v
	return nil
}
