// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"encoding/binary"
	"github.com/go-faster/errors"
)

// ClickHouse uses LittleEndian.
var _ = binary.LittleEndian

// ColUInt32 represents UInt32 column.
type ColUInt32 []uint32

// Compile-time assertions for ColUInt32.
var (
	_ ColInput  = ColUInt32{}
	_ ColResult = (*ColUInt32)(nil)
	_ Column    = (*ColUInt32)(nil)
)

// Type returns ColumnType of UInt32.
func (ColUInt32) Type() ColumnType {
	return ColumnTypeUInt32
}

// Rows returns count of rows in column.
func (c ColUInt32) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColUInt32) Reset() {
	*c = (*c)[:0]
}

// NewArrUInt32 returns new Array(UInt32).
func NewArrUInt32() *ColArr {
	return &ColArr{
		Data: new(ColUInt32),
	}
}

// AppendUInt32 appends slice of uint32 to Array(UInt32).
func (c *ColArr) AppendUInt32(data []uint32) {
	d := c.Data.(*ColUInt32)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}

// EncodeColumn encodes UInt32 rows to *Buffer.
func (c ColUInt32) EncodeColumn(b *Buffer) {
	const size = 32 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c))...)
	for _, v := range c {
		binary.LittleEndian.PutUint32(
			b.Buf[offset:offset+size],
			v,
		)
		offset += size
	}
}

// DecodeColumn decodes UInt32 rows from *Reader.
func (c *ColUInt32) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := append(*c, make([]uint32, rows)...)

	var (
		n = 0
		i = 0
	)
	const (
		unroll         = 4
		unrollByteSize = size * unroll
	)
	if len(data) > unrollByteSize {
		_ = data[:len(data)-unrollByteSize]
		for i = 0; i <= len(data)-unrollByteSize; i += unrollByteSize {
			src := [unroll]uint32{}
			const offset0 = 0 + size + size + size
			src[3] =
				binary.LittleEndian.Uint32(data[i+offset0 : i+offset0+size : i+offset0+size])
			const offset1 = 0 + size + size
			src[2] =
				binary.LittleEndian.Uint32(data[i+offset1 : i+offset1+size : i+offset1+size])
			const offset2 = 0 + size
			src[1] =
				binary.LittleEndian.Uint32(data[i+offset2 : i+offset2+size : i+offset2+size])
			const offset3 = 0
			src[0] =
				binary.LittleEndian.Uint32(data[i+offset3 : i+offset3+size : i+offset3+size])
			copy(v[n:n+unroll:n+unroll], src[:])
			n += unroll
		}
	}
	for _ = i; i < len(data); i += size {
		v[n] =
			binary.LittleEndian.Uint32(data[i:])
		n++
	}
	*c = v
	return nil
}
