// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"encoding/binary"
	"github.com/go-faster/errors"
	"math"
)

// ClickHouse uses LittleEndian.
var _ = binary.LittleEndian

// ColFloat32 represents Float32 column.
type ColFloat32 []float32

// Compile-time assertions for ColFloat32.
var (
	_ ColInput  = ColFloat32{}
	_ ColResult = (*ColFloat32)(nil)
	_ Column    = (*ColFloat32)(nil)
)

// Type returns ColumnType of Float32.
func (ColFloat32) Type() ColumnType {
	return ColumnTypeFloat32
}

// Rows returns count of rows in column.
func (c ColFloat32) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColFloat32) Reset() {
	*c = (*c)[:0]
}

// NewArrFloat32 returns new Array(Float32).
func NewArrFloat32() *ColArr {
	return &ColArr{
		Data: new(ColFloat32),
	}
}

// AppendFloat32 appends slice of float32 to Array(Float32).
func (c *ColArr) AppendFloat32(data []float32) {
	d := c.Data.(*ColFloat32)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}

// EncodeColumn encodes Float32 rows to *Buffer.
func (c ColFloat32) EncodeColumn(b *Buffer) {
	const size = 32 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c))...)
	for _, v := range c {
		binary.LittleEndian.PutUint32(
			b.Buf[offset:offset+size],
			math.Float32bits(v),
		)
		offset += size
	}
}

// DecodeColumn decodes Float32 rows from *Reader.
func (c *ColFloat32) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := append(*c, make([]float32, rows)...)

	var (
		n = 0
		i = 0
	)
	const (
		unroll         = 4
		unrollByteSize = size * unroll
	)
	if len(data) > unrollByteSize {
		_ = data[:len(data)-unrollByteSize]
		for i = 0; i <= len(data)-unrollByteSize; i += unrollByteSize {
			src := [unroll]float32{}
			const offset0 = 0 + size + size + size
			src[3] =
				math.Float32frombits(bin.Uint32(data[i+offset0 : i+offset0+size : i+offset0+size]))
			const offset1 = 0 + size + size
			src[2] =
				math.Float32frombits(bin.Uint32(data[i+offset1 : i+offset1+size : i+offset1+size]))
			const offset2 = 0 + size
			src[1] =
				math.Float32frombits(bin.Uint32(data[i+offset2 : i+offset2+size : i+offset2+size]))
			const offset3 = 0
			src[0] =
				math.Float32frombits(bin.Uint32(data[i+offset3 : i+offset3+size : i+offset3+size]))
			copy(v[n:n+unroll:n+unroll], src[:])
			n += unroll
		}
	}
	for _ = i; i < len(data); i += size {
		v[n] =
			math.Float32frombits(bin.Uint32(data[i:]))
		n++
	}
	*c = v
	return nil
}
