// Code generated by ./cmd/ch-gen-int, DO NOT EDIT.

package proto

import (
	"encoding/binary"
	"github.com/go-faster/errors"
)

// ClickHouse uses LittleEndian.
var _ = binary.LittleEndian

// ColInt32 represents Int32 column.
type ColInt32 []int32

// Compile-time assertions for ColInt32.
var (
	_ ColInput  = ColInt32{}
	_ ColResult = (*ColInt32)(nil)
	_ Column    = (*ColInt32)(nil)
)

// Type returns ColumnType of Int32.
func (ColInt32) Type() ColumnType {
	return ColumnTypeInt32
}

// Rows returns count of rows in column.
func (c ColInt32) Rows() int {
	return len(c)
}

// Reset resets data in row, preserving capacity for efficiency.
func (c *ColInt32) Reset() {
	*c = (*c)[:0]
}

// NewArrInt32 returns new Array(Int32).
func NewArrInt32() *ColArr {
	return &ColArr{
		Data: new(ColInt32),
	}
}

// AppendInt32 appends slice of int32 to Array(Int32).
func (c *ColArr) AppendInt32(data []int32) {
	d := c.Data.(*ColInt32)
	*d = append(*d, data...)
	c.Offsets = append(c.Offsets, uint64(len(*d)))
}

// EncodeColumn encodes Int32 rows to *Buffer.
func (c ColInt32) EncodeColumn(b *Buffer) {
	const size = 32 / 8
	offset := len(b.Buf)
	b.Buf = append(b.Buf, make([]byte, size*len(c))...)
	for _, v := range c {
		binary.LittleEndian.PutUint32(
			b.Buf[offset:offset+size],
			uint32(v),
		)
		offset += size
	}
}

// DecodeColumn decodes Int32 rows from *Reader.
func (c *ColInt32) DecodeColumn(r *Reader, rows int) error {
	if rows == 0 {
		return nil
	}
	const size = 32 / 8
	data, err := r.ReadRaw(rows * size)
	if err != nil {
		return errors.Wrap(err, "read")
	}
	v := append(*c, make([]int32, rows)...)

	var (
		n = 0
		i = 0
	)
	const (
		unroll         = 4
		unrollByteSize = size * unroll
	)
	if len(data) > unrollByteSize {
		_ = data[:len(data)-unrollByteSize]
		for i = 0; i <= len(data)-unrollByteSize; i += unrollByteSize {
			src := [unroll]int32{}
			const offset0 = 0 + size + size + size
			src[3] =
				int32(binary.LittleEndian.Uint32(data[i+offset0 : i+offset0+size : i+offset0+size]))
			const offset1 = 0 + size + size
			src[2] =
				int32(binary.LittleEndian.Uint32(data[i+offset1 : i+offset1+size : i+offset1+size]))
			const offset2 = 0 + size
			src[1] =
				int32(binary.LittleEndian.Uint32(data[i+offset2 : i+offset2+size : i+offset2+size]))
			const offset3 = 0
			src[0] =
				int32(binary.LittleEndian.Uint32(data[i+offset3 : i+offset3+size : i+offset3+size]))
			copy(v[n:n+unroll:n+unroll], src[:])
			n += unroll
		}
	}
	for _ = i; i < len(data); i += size {
		v[n] =
			int32(binary.LittleEndian.Uint32(data[i:]))
		n++
	}
	*c = v
	return nil
}
